employeeproject/employee/urls.py
from django.urls import path, include
from employee import views
app_name='employee'

urlpatterns = [

    path('',views.home,name="home"),
    path('add/',views.add,name="add"),
    path('view/',views.viewemp,name='viewemp'),
    path('detail/<int:pk>',views.detail,name='detail'),
    path('update/<int:pk>',views.update,name="update"),
    path('delete/<int:pk>',views.delete,name="delete"),
    path('viewdepemp/<int:pk>',views.viewdepemp,name="viewdepemp"),
    path('register/',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
]

employeeproject/employeeproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('employee.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employeeproject/employee/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class Company(models.Model):
    id=models.IntegerField(primary_key=True,auto_created=True)
    name=models.CharField(max_length=100)
    address=models.TextField()

    def __str__(self):
        return self.name

class Department(models.Model):
    id=models.IntegerField(auto_created=True,primary_key=True)
    name=models.CharField(max_length=70)

    def __str__(self):
        return self.name

class Employee(models.Model):
    id=models.IntegerField(primary_key=True,auto_created=True)
    image=models.ImageField(upload_to='employee/images',blank=True,null=True)
    name=models.CharField(max_length=50)
    age=models.IntegerField()
    company=models.ForeignKey(Company,on_delete=models.CASCADE)
    department=models.ForeignKey(Department,on_delete=models.CASCADE)
    address=models.TextField()
    phone_number=models.IntegerField()
    salary=models.IntegerField()
    joined_date=models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.name


class CustomUser(AbstractUser):
    phone=models.IntegerField(default=0)
    address=models.TextField(default="")


    def __str__(self):
        return self.username

employeeproject/employee/forms.py
from django.forms import ModelForm
from employee.models import Employee

class EmployeeForm(ModelForm):
    class Meta:
        model=Employee
        fields='__all__'

employeeproject/employee/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from employee.models import Employee,Company,Department,CustomUser
from employee.forms import EmployeeForm
# Create your views here.


def home(request):
    c=Company.objects.all()
    d=Department.objects.all()
    return render(request,"home.html",{'c':c,'d':d})


# def add(request):
#     c = Company.objects.all()
#     d = Department.objects.all()
#
#     if (request.method == 'POST'):
#         name = request.POST['name']
#         age = request.POST['age']
#         company = request.POST['company']
#         department = request.POST['department']
#         address = request.POST['address']
#         image = request.FILES['image']
#         phone_number = request.POST['phone']
#         salary = request.POST['salary']
#
#         d=Department.objects.get(name=department)
#         c=Company.objects.get(name=company)
#
#         e = Employee.objects.create(name=name,age=age,company=c,department=d,address=address,image=image,phone_number=phone_number,salary=salary)
#         e.save()
#
#         return render(request, "addemo.html", {'c': c, 'd': d})
#
@login_required
def add(request):


    if(request.method=='POST'):

        form=EmployeeForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return home(request)
    form=EmployeeForm()

    return render(request,"addemo.html",{'f':form},)


@login_required()
def viewemp(request):
    e=Employee.objects.all()
    return render(request,"viewemp.html",{'e':e})


@login_required()
def detail(request,pk):

    e=Employee.objects.filter(id=pk)


    return render(request,"detailview.html",{'h':e})

@login_required()
def update(request,pk):
    e=Employee.objects.get(id=pk)

    if(request.method=='POST'):
        form=EmployeeForm(request.POST,request.FILES,instance=e)
        if form.is_valid():
            form.save()
            return viewemp(request)


    form=EmployeeForm(instance=e)

    return (
        render(request,"update.html",{'form':form}))

@login_required()
def delete(request,pk):

    e=Employee.objects.filter(id=pk)
    e.delete()

    return viewemp(request)
@login_required()
def viewdepemp(request,pk):

    c=Company.objects.get(id=pk)
    e=Employee.objects.filter(company=c)
    return render(request,"viewdepemp.html",{'e':e})

def register(request):

    if(request.method=='POST'):
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        email = request.POST['email']
        phonenumber = request.POST['phone']
        address = request.POST['address']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']

        if (cpassword == password):
            user = CustomUser.objects.create_user(username=username, password=password, email=email,
                                                  first_name=first_name, last_name=last_name, phone=phonenumber,
                                                  address=address)
            user.save()
            return redirect('employee:login')
        else:
            return HttpResponse("Password does not match")

    return render(request,"register.html")

def login(request):
    if(request.method=='POST'):
        username=request.POST['username']
        password=request.POST['password']

        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('employee:home')
        else:
            return HttpResponse('Invalid username and Password')

    return render(request,"login.html")
@login_required()
def logout(request):
    auth.logout(request)
    return redirect('employee:login')

employeeproject/templates/addemo.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
ADD EMPLOYEE
{% endblock %}

{% block content %}

<!--<h5 class="text-center text-primary">ADD EMPLOYEE</h5>-->

<div class="container mt-5">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
<!--      <div class="mb-3">-->
<!--        <label class="form-label">Name:</label>-->
<!--        <input type="text" class="form-control" id="title" name="name">-->
<!--    &lt;!&ndash;    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>&ndash;&gt;-->
<!--      </div>-->



<!--      <div class="mb-3">-->
<!--        <label for="age" class="form-label">Age:</label>-->
<!--        <input type="number" class="form-control" id="age" name="age">-->
<!--      </div>-->

<!--      <div class="mb-3">-->
<!--        <label  class="form-label">Company:</label>-->

<!--        <select name="company" id="cars">-->
<!--          {% for i in c %}-->
<!--          <option value="{{i.name}}">{{i.name}}</option>-->
<!--&lt;!&ndash;          <option value="Wipro">Wipro</option>&ndash;&gt;-->
<!--&lt;!&ndash;          <option value="mercedes">Mercedes</option>&ndash;&gt;-->
<!--&lt;!&ndash;          <option value="audi">Audi</option>&ndash;&gt;-->
<!--          {% endfor %}-->
<!--        </select>-->

<!--      </div>-->

<!--      <div class="mb-3">-->
<!--        <label class="form-label">Department:</label>-->

<!--        <select name="department" >-->
<!--          {% for i in d %}-->
<!--          <option value="{{i.name}}">{{i.name}}</option>-->
<!--&lt;!&ndash;          <option value="Developer">Developer</option>&ndash;&gt;-->
<!--&lt;!&ndash;          <option value="Technical">Technical</option>&ndash;&gt;-->
<!--&lt;!&ndash;          <option value="audi">Audi</option>&ndash;&gt;-->
<!--          {% endfor %}-->
<!--        </select>-->

<!--      </div>-->
<!--      <div class="mb-3">-->
<!--        <label for="address" class="form-label">Address:</label>-->
<!--        <input type="text" class="form-control" id="address" name="address">-->
<!--      </div>-->
<!--      <div class="mb-3">-->
<!--        <label for="image" class="form-label">Image:</label>-->
<!--        <input type="file" class="form-control" id="image" name="image">-->
<!--      </div>-->
<!--      <div class="mb-3">-->
<!--        <label for="phone" class="form-label">Phone number:</label>-->
<!--        <input type="number" class="form-control" id="phone" name="phone">-->
<!--      </div>-->
<!--      <div class="mb-3">-->
<!--        <label for="salary" class="form-label">Salary:</label>-->
<!--        <input type="number" class="form-control" id="Salary" name="salary">-->
<!--      </div>-->
          {{f|crispy}}
        <center>
      <button type="submit" class="btn btn-primary">Submit</button>
            </center>
    </form>
</div>


{% endblock %}

employeeproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</head>
<body style="background-color:lightgreen;">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand text-danger" href="#">EMPLOYEE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'employee:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'employee:add' %}">Add Employee</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'employee:viewemp' %}">View Employee</a>
        </li>
<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            Dropdown-->
<!--          </a>-->
<!--          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--            <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
<!--          </ul>-->
<!--        </li>-->
        {% if user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link " href="{% url 'employee:logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
        </li>
        {% else %}

        <li class="nav-item">
           <li class="nav-item">
          <a class="nav-link " href="{% url 'employee:login' %}" tabindex="-1" aria-disabled="true">Login</a>
        </li>
          <a class="nav-link " href="{% url 'employee:register' %}" tabindex="-1" aria-disabled="true">Register</a>
        </li>
        {% endif %}

      </ul>
<!--      <form class="d-flex">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--      </form>-->
<!--    </div>-->
  </div>
</nav>


{% block content %}

{% endblock %}



</body>
</html>

employeeproject/templates/detailview.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
DETAIL
{% endblock %}


{% block content %}
<h5 class="text-center text-primary">Employee Details</h5>


<div class="container mt-5 bg-white p-5" >
    <table class="table table-bordered table-stripped ">
        {% for i in h %}
        <center><img class="mb-3" src="{{i.image.url}}" height="250px" width="250px"></center>
        <tr>
            <th>Emp Id:</th>
            <td>{{i.id}}</td>
        </tr>
        <tr>
            <th class="text-primary">Name:</th>
            <td class="text-primary"><b>{{i.name}}</b></td>
        </tr>
        <tr>
            <th>Age:</th>
            <td>{{i.age}}</td>

        </tr>
        <tr>
            <th>Company:</th>
            <td>{{i.company}}</td>
        </tr>
        <tr>
            <th class="text-danger">Department:</th>
            <td class="text-danger"><b>{{i.department}}</b></td>

        </tr>
        <tr>
            <th>Address:</th>
            <td>{{i.address}}</td>
        </tr>
        <tr>
            <th>Phone Number:</th>
            <td>{{i.phone_number}}</td>
        </tr>
        <tr>
            <th>Salary:</th>
            <td>{{i.salary}}</td>
        </tr>
        <tr>
            <th>Joined Date:</th>
            <td>{{i.joined_date}}</td>
        </tr>


    </table>
    <a href="{% url 'employee:update' i.id %}"><button class="btn btn-warning" style="margin-left:40%;">UPDATE</button></a>
    {% endfor %}
</div>






{% endblock %}

employeeproject/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
HOME
{% endblock %}

{% block content %}
<h5 class="text-center text-primary ">WELCOME TO HOME PAGE</h5>
{% if user.is_authenticated %}
<div class="container mt-5 bg-dark p-3">
    <h6 class="text-primary my-3">COMPANY:</h6>
    <table class="table table-bordered table-stripped">
        <tr>
            <th class="text-white text-center">ID</th>
            <th class="text-white text-center">NAME</th>
             <th class="text-white text-center">WORKING EMPLOYEES</th>
        </tr>
        {% for i in c %}
        <tr>
            <td class="text-white text-center">{{i.id}}</td>
            <td class="text-white text-center">{{i.name}}</td>
            <td class="text-primary"><a href="{% url 'employee:viewdepemp' i.id %}"><button style="margin-left:45%;" class="btn btn-primary">VIew</button></a></td>
        </tr>
        {% endfor %}
    </table>
</div>


<div class="container mt-5 bg-dark p-3">
    <h6 class="text-primary my-3">DEPARTMENTS:</h6>
    <table class="table table-bordered table-stripped">
        <tr>
            <th class="text-white ">ID</th>
            <th class="text-white">NAME</th>

        </tr>
        {% for i in d %}
        <tr>
            <td class="text-white">{{i.id}}</td>
            <td class="text-white">{{i.name}}</td>

        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}
{% endblock %}

employeeproject/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Login

{% endblock %}

{% block content %}

<div class="container mt-5">
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3">
    <label for="username" class="form-label">User Name:</label>
    <input type="text" class="form-control" id="username" aria-describedby="username" name="username">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <center>
  <button type="submit" class="btn btn-primary mt-3" >Submit</button>
    </center>
</form>
  </div>
{% endblock %}

employeeproject/templates/register.html
{% extends 'base.html' %}
{% load  static %}

{% block title %}
REGISTER
{% endblock %}

{% block content %}

<div class="container mt-5" >
  <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        <label class="form-label">User Name:</label>
        <input type="text" class="form-control" id="name" name="username">
    <!--    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>-->
      </div>



      <div class="mb-3">
        <label for="password" class="form-label">Password:</label>
        <input type="password" class="form-control" id="password" name="password">
      </div>


      <div class="mb-3">
        <label class="form-label">Confirm Password:</label>
        <input type="password" class="form-control" id="cpassword" name="cpassword">
      </div>


      <div class="mb-3">
        <label class="form-label">Email:</label>
        <input type="email" class="form-control" id="email" name="email">
      </div>
      <div class="mb-3">
        <label class="form-label">Phone Number:</label>
        <input type="number" class="form-control" id="phonenumber" name="phone">
      </div>

      <div class="mb-3">
       <div class="form-floating">

      <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea" name="address"></textarea>
      <label for="floatingTextarea">Address:</label>
    </div>


      <div class="mb-3">
        <label class="form-label">First Name:</label>
        <input type="text" class="form-control" id="firstname" name="first_name">
      </div>


      <div class="mb-3">
        <label for="lastname" class="form-label">Last Name:</label>
        <input type="text" class="form-control" id="lastname" name="last_name">
        <center>
        <button type="submit" class="btn btn-warning mt-2">Submit</button>
            </center>
      </div>
  </form>
</div>


{% endblock %}

employeeproject/templates/update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
UPDATE
{% endblock %}

{% block content %}
<div class="container mt-5">
    <form method="POST" enctype="multipart/form-data">
         {% csrf_token %}
        {{form|crispy}}

        <button type="submit" class="btn btn-warning mb-5" style="margin-left:50%;">Submit</button>
    </form>


    </div>


{% endblock%}

employeeproject/templates/viewdepemp.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
DEP EMP
{% endblock %}

{% block content %}

<h5 class="text-center text-primary">DEP EMP</h5>
<div class="container-fluid bg-white p-5 mt-5">
<table class="table table-bordered table-stripped  ">
    <tr>
        <th class="text-center" >EMP ID</th>
        <th class="text-center">NAME</th>

    </tr>
    {% for i in e %}
    <tr>
        <td class="text-center">{{i.id}}</td>
        <td class="text-danger text-center">{{i.name}}</td>
    </tr>
    {% endfor %}
</table>

    </div>

{% endblock %}

employeeproject/templates/viewemp.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
VIEW DETAIL
{% endblock %}


{% block content %}

<div class="container mt-5 mb-5 bg-white p-5">
    <table class="table table-bordered table-stripped  ">
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Name</th>
            <th>Age</th>
            <th>Company</th>
            <th>Department</th>
            <th>Address</th>
            <th>Details</th>
            <th>Delete</th>

        </tr>
        {% for i in e %}
        <tr>
            <th>{{i.id}}</th>
            <th><img src="{{i.image.url}}" height="200px" width="200px"></th>
            <td class="text-primary" style="width:200px;text-align:center;padding-top:80px;">{{i.name}}</td>
            <td style="width:200px;text-align:center;padding-top:80px;">{{i.age}}</td>
            <td style="width:200px;text-align:center;padding-top:80px;">{{i.company}}</td>
            <td style="width:200px;text-align:center;padding-top:80px;">{{i.department}}</td>
            <td style="padding-top:70px;">{{i.address}}</td>
            <td style="padding-top:70px;"><a href="{% url 'employee:detail' i.id %}"><button class="btn btn-primary" >View</button></a></td>
            <td style="padding-top:70px;"><a href="{% url 'employee:delete' i.id %}"><button class="btn btn-danger" >Delete</button></a></td>
        </tr>
        {% endfor %}
    </table>
</div>


{% endblock %}